`timescale 1ns/1ps
// uJ11 M0: a small predecoder dispatches directly into the microcoded engine.
// All architectural execution, including PC+2 and BR, uses the shared ALU/RF.
module uj11_core #(parameter integer ROM_DECODE=0, ALIGNED_WORD_READS=0, IRQ_VECTOR_BITS=8, parameter [15:0] UNMASKED_VECTOR=0) (
    input wire clk, reset,
    input wire irq_valid,
    input wire [2:0] irq_priority,
    input wire [IRQ_VECTOR_BITS:1] irq_vector,
    output wire irq_ack, waiting, peripheral_reset,
    output wire [15:0] mem_addr, mem_write_data,
    output wire mem_request, mem_read, mem_write, mem_byte,
    output wire mem_bank, mem_physical,
    input wire mem_ack, mem_error,
    input wire [15:0] mem_read_data,
    output wire stopped,
    output wire [1:0] fault_code,
    output wire retire,
    output wire [9:0] debug_upc,
    output wire [35:0] debug_uword,
    output wire [15:0] ir, mdr, psw, q,
    output wire debug_rf_write,
    output wire [3:0] debug_rf_address,
    output wire [15:0] debug_rf_data
);
    wire [15:0] dispatch_ir;
    wire [9:0] dispatch_address;
    // A board may return an aligned word for every read. FETCH always reads
    // a word; keep its ROM input ahead of the operand-only byte-lane mux.
    // The default preserves the established right-justified core interface.
    wire [15:0] operand_read_data = (ALIGNED_WORD_READS!=0 && mem_byte) ?
        (mem_addr[0] ? {8'b0,mem_read_data[15:8]} : {8'b0,mem_read_data[7:0]}) : mem_read_data;
    generate if(ROM_DECODE!=0)begin: sync_decode
        wire fetch=debug_uword[35] && debug_uword[34:31]==4'd2;
        uj11_decode_rom decode(.clk(clk),.enable(fetch && mem_request && mem_ack && !mem_error),
            .incoming(mem_read_data),.entry(dispatch_address));
    end else begin: logic_decode
        uj11_decode decode(.ir(dispatch_ir),.entry(dispatch_address));
    end endgenerate
    uj11_engine #(.ROM_DECODE(ROM_DECODE),.IRQ_VECTOR_BITS(IRQ_VECTOR_BITS),.UNMASKED_VECTOR(UNMASKED_VECTOR)) engine(.clk(clk),.reset(reset),
        .irq_valid(irq_valid),.irq_priority(irq_priority),.irq_vector(irq_vector),.irq_ack(irq_ack),.waiting(waiting),.peripheral_reset(peripheral_reset),.dispatch_address(dispatch_address),
        .dispatch_ir(dispatch_ir),.mem_addr(mem_addr),.mem_write_data(mem_write_data),
        .mem_bank(mem_bank),.mem_physical(mem_physical),.mem_request(mem_request),.mem_read(mem_read),.mem_write(mem_write),.mem_byte(mem_byte),
        .mem_ack(mem_ack),.mem_error(mem_error),.mem_read_data(operand_read_data),
        .stopped(stopped),.fault_code(fault_code),.retire(retire),.debug_upc(debug_upc),
        .debug_uword(debug_uword),.ir(ir),.mdr(mdr),.psw(psw),.q(q),
        .debug_rf_write(debug_rf_write),.debug_rf_address(debug_rf_address),.debug_rf_data(debug_rf_data));
endmodule

`timescale 1ns/1ps
// CP36: every opcode and enable hold is checked against the old dispatch.
module uj11_decode_rom(input wire clk, enable,
    input wire [15:0] incoming, output wire [9:0] entry);
    wire [15:0] op = incoming;
    wire system_low = ~|op[15:8];
    wire single_group = ~|op[14:12];
    wire eis_group = op[15:12]==4'h7;
    wire memory_mode = |op[5:3];
    wire [9:0] index;
    assign index[9] = system_low || eis_group;
    assign index[8] = single_group;
    // EIS already has op[15]=0; both other non-system pages use op[15].
    assign index[7] = system_low ? op[7] : op[15];
    assign index[6] = system_low ? op[6] : single_group ? op[11] : (!eis_group && op[14]);
    assign index[5] = system_low ? op[5] : single_group ? op[10] : eis_group ? op[11] : op[13];
    assign index[4] = system_low ? op[4] : single_group ? op[9] : eis_group ? op[10] : op[12];
    assign index[3] = system_low ? op[3] : single_group ? op[8] : eis_group ? op[9] : (|op[11:9]);
    assign index[2] = system_low ? op[2] : single_group ? op[7] : eis_group ? (|op[8:6]) : memory_mode;
    assign index[1] = system_low ? op[1] : single_group ? op[6] : (eis_group && op[5]);
    assign index[0] = system_low ? op[0] : ((single_group || eis_group) && memory_mode);
    uj11_decode_table table_rom(.clk(clk),.enable(enable),.address(index),.data(entry[8:0]));
    assign entry[9]=0;
endmodule

// GENERATED by tools/make_ebr.py; do not edit.
`timescale 1ns/1ps
module uj11_decode_table #(parameter IMAGE = "unused") (
    input wire clk, enable, input wire [9:0] address,
    output wire [8:0] data
);
`ifdef SYNTHESIS
`define UJ11_DECODE_EBR
`elsif UJ11_VENDOR_ROM
`define UJ11_DECODE_EBR
`endif
`ifdef UJ11_DECODE_EBR
    DP8KC #(
        .DATA_WIDTH_A(9), .DATA_WIDTH_B(9),
        .REGMODE_A("NOREG"), .REGMODE_B("NOREG"),
        .CSDECODE_A("0b000"), .CSDECODE_B("0b111"),
        .WRITEMODE_A("NORMAL"), .WRITEMODE_B("NORMAL"),
        .GSR("DISABLED"), .RESETMODE("SYNC"),
        .ASYNC_RESET_RELEASE("SYNC"), .INIT_DATA("STATIC"),
        .INITVAL_00("0x08442085180844208518084420851808442085100844208442084420844208442084420844208442"),
        .INITVAL_01("0x08442085380844208538084420853808442085300844208528084420852808442085280844208520"),
        .INITVAL_02("0x08442085580844208558084420855808442085500844208548084420854808442085480844208540"),
        .INITVAL_03("0x08442084420844208442084420844208442084420844208568084420856808442085680844208560"),
        .INITVAL_04("0x08442085180844208518084420851808442085100844208442084420844208442084420844208442"),
        .INITVAL_05("0x08442085380844208538084420853808442085300844208528084420852808442085280844208520"),
        .INITVAL_06("0x08442085580844208558084420855808442085500844208548084420854808442085480844208540"),
        .INITVAL_07("0x084420842D084420842D084420842D084420842D08442085E808442085E808442085E808442085E0"),
        .INITVAL_08("0x0984C0984C0984C0984C090480904809048090480884408844088440884408442084420844208442"),
        .INITVAL_09("0x0B85C0B85C0B85C0B85C0B0580B0580B0580B0580A8540A8540A8540A8540A0500A0500A0500A050"),
        .INITVAL_0A("0x17CBC174B816CB4164B015CAC154A814CA4144A01104211042110421104211042110421104211042"),
        .INITVAL_0B("0x0844208442084420844208442084420844208442369B00844208442341A019CCC194C818CC4184C0"),
        .INITVAL_0C("0x0D86C0D86C0D86C0D86C0D0680D0680D0680D0680C8640C8640C8640C8640C0600C0600C0600C060"),
        .INITVAL_0D("0x0F87C0F87C0F87C0F87C0F0780F0780F0780F0780E8740E8740E8740E8740E0700E0700E0700E070"),
        .INITVAL_0E("0x17CBC174B816CB4164B015CAC154A814CA4144A00542A0542A0542A0542A05028050280502805028"),
        .INITVAL_0F("0x08442084420844208442084420844208442084423B5D80844208442355A819CCC194C818CC4184C0"),
        .INITVAL_10("0x038420381C038420381C032420321903242032190EC420EC720EC420EC720CC420CC620CC420CC62"),
        .INITVAL_11("0x13042130981304213098084420844208442084420844208442084420221105C4205C2C05C4205C2C"),
        .INITVAL_12("0x08442084420844208442084420844208442084420844208442084420844208442084420844208442"),
        .INITVAL_13("0x08442084420844208442084420844208442084420844208442084420844208442084420844208442"),
        .INITVAL_14("0x08442084420844208442084420844208442084420844208442084420844208442084420844208442"),
        .INITVAL_15("0x08442084420844208442084420844208442084420844208442084420844208442084420844208442"),
        .INITVAL_16("0x08442084420844208442084420844208442084420844208442084420844208442084420844208442"),
        .INITVAL_17("0x08442084420844208442084420844208442084420844208442084420844208442084420844208442"),
        .INITVAL_18("0x25D2E25D2E24D2626C4223D1E23D1E22D1615AB1084420844221D0E21D0E02E31042260483102453"),
        .INITVAL_19("0x08442084420844208442084420844208442084420844208442084420844208442152A51426F0D657"),
        .INITVAL_1A("0x10080100801008010080100801008010080100801008010080100801008008040080400804008040"),
        .INITVAL_1B("0x10080100801008010080100801008010080100801008010080100801008010080100801008010080"),
        .INITVAL_1C("0x3FDFC3F5F83EDF43E5F0084420844208442084420844208442084420844212090120901209012090"),
        .INITVAL_1D("0x2F9742D9642B95429944279342592423914219042F9742D9642B9542994427934259242391421904"),
        .INITVAL_1E("0x391C8391C8391C8391C8391C8391C8391C8391C8391C8391C8391C8391C8381C0381C0381C0381C0"),
        .INITVAL_1F("0x391C8391C8391C8391C8391C8391C8391C8391C8391C8391C8391C8391C8391C8391C8391C8391C8")
    ) lane_0 (
        .DIA0(1'b0),
        .DIA1(1'b0),
        .DIA2(1'b0),
        .DIA3(1'b0),
        .DIA4(1'b0),
        .DIA5(1'b0),
        .DIA6(1'b0),
        .DIA7(1'b0),
        .DIA8(1'b0),
        .ADA0(1'b1),
        .ADA1(1'b0),
        .ADA2(1'b0),
        .ADA3(address[0]),
        .ADA4(address[1]),
        .ADA5(address[2]),
        .ADA6(address[3]),
        .ADA7(address[4]),
        .ADA8(address[5]),
        .ADA9(address[6]),
        .ADA10(address[7]),
        .ADA11(address[8]),
        .ADA12(address[9]),
        .CEA(enable),
        .OCEA(enable),
        .CLKA(clk),
        .WEA(1'b0),
        .RSTA(1'b0),
        .CSA0(1'b0),
        .CSA1(1'b0),
        .CSA2(1'b0),
        .DOA0(data[0]),
        .DOA1(data[1]),
        .DOA2(data[2]),
        .DOA3(data[3]),
        .DOA4(data[4]),
        .DOA5(data[5]),
        .DOA6(data[6]),
        .DOA7(data[7]),
        .DOA8(data[8]),
        .DIB0(1'b0),
        .DIB1(1'b0),
        .DIB2(1'b0),
        .DIB3(1'b0),
        .DIB4(1'b0),
        .DIB5(1'b0),
        .DIB6(1'b0),
        .DIB7(1'b0),
        .DIB8(1'b0),
        .ADB0(1'b0),
        .ADB1(1'b0),
        .ADB2(1'b0),
        .ADB3(1'b0),
        .ADB4(1'b0),
        .ADB5(1'b0),
        .ADB6(1'b0),
        .ADB7(1'b0),
        .ADB8(1'b0),
        .ADB9(1'b0),
        .ADB10(1'b0),
        .ADB11(1'b0),
        .ADB12(1'b0),
        .CEB(1'b0),
        .OCEB(1'b0),
        .CLKB(1'b0),
        .WEB(1'b0),
        .RSTB(1'b0),
        .CSB0(1'b0),
        .CSB1(1'b0),
        .CSB2(1'b0),
        .DOB0(),
        .DOB1(),
        .DOB2(),
        .DOB3(),
        .DOB4(),
        .DOB5(),
        .DOB6(),
        .DOB7(),
        .DOB8()
    );
`else
    reg [8:0] words[0:1023]; reg [8:0] value;
    initial $readmemh("build/cp57-service/decode.mem",words);
    always @(posedge clk) if(enable) value<=words[address];
    assign data=value;
`endif
`undef UJ11_DECODE_EBR
endmodule
