#!/usr/bin/env python3
"""Assemble PDP-11 board firmware and emit one dual-port 1024x9 EBR (512 words)."""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
from make_ebr import lane_initvals

ROOT = Path(__file__).resolve().parents[1]


def generate(words):
    halves = [part for w in words for part in (w & 255, w >> 8)]
    lines = ['// Generated by tools/build_firmware.py; one EBR, two byte ports.',
             '`timescale 1ns/1ps', 'module uj11_firmware_rom(',
             ' input wire clk, enable, input wire [8:0] address, output wire [15:0] data,',
             ' input wire [1:0] write_enable, input wire [15:0] write_data);',
             " wire [1:0] write_lanes=write_enable & {2{address[8:4]==5'b01111}};",
             '`ifdef SYNTHESIS', '`define UJ11_FW_EBR',
             '`elsif UJ11_VENDOR_ROM', '`define UJ11_FW_EBR', '`endif',
             '`ifdef UJ11_FW_EBR', ' DP8KC #(',
             ' .DATA_WIDTH_A(9), .DATA_WIDTH_B(9), .REGMODE_A("NOREG"), .REGMODE_B("NOREG"),',
             ' .CSDECODE_A("0b000"), .CSDECODE_B("0b000"),',
             ' .WRITEMODE_A("NORMAL"), .WRITEMODE_B("NORMAL"),',
             ' .GSR("DISABLED"), .RESETMODE("SYNC"), .ASYNC_RESET_RELEASE("SYNC"), .INIT_DATA("STATIC"),']
    lines += [f' .INITVAL_{i:02X}("0x{v:080X}"){"," if i < 31 else ""}'
              for i, v in enumerate(lane_initvals(halves, 0))]
    lines.append(' ) firmware (')
    ports = []
    for side in 'AB':
        ports += [(f'DI{side}{i}', f'write_data[{i+(8 if side=="B" else 0)}]' if i<8 else "1'b0") for i in range(9)]
        for i in range(13):
            value = f'address[{i-4}]' if i >= 4 else (
                "1'b1" if i == 0 or (i == 3 and side == 'B') else "1'b0")
            ports.append((f'AD{side}{i}', value))
        ports += [(f'CE{side}', 'enable'), (f'OCE{side}', 'enable'), (f'CLK{side}', 'clk'),
                  (f'WE{side}', f'write_lanes[{1 if side=="B" else 0}]'), (f'RST{side}', "1'b0")]
        ports += [(f'CS{side}{i}', "1'b0") for i in range(3)]
        ports += [(f'DO{side}{i}', f'data[{i+(8 if side == "B" else 0)}]' if i < 8 else '') for i in range(9)]
    lines += [f' .{n}({v}){"," if i < len(ports)-1 else ""}' for i, (n, v) in enumerate(ports)]
    lines += [' );', '`else', ' reg [15:0] words[0:511]; reg [15:0] value;',
              ' initial $readmemh("microcode/generated/firmware.mem", words);',
              ' always @(posedge clk) if(enable) begin',
              '  value <= words[address];',
              '  if(write_lanes[0])words[address][7:0]<=write_data[7:0];',
              '  if(write_lanes[1])words[address][15:8]<=write_data[15:8];',
              ' end',
              ' assign data=value;', '`endif', '`undef UJ11_FW_EBR', 'endmodule', '']
    return '\n'.join(lines)


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--assembler', default=str(ROOT/'../microasm11/microasm11'))
    args = p.parse_args()
    out = ROOT/'build/firmware'; out.mkdir(parents=True, exist_ok=True)
    words = [0]*512
    report = {}
    for name, offset in [('sd_boot', 0), ('rk_service', 256)]:
        source = ROOT/f'firmware/{name}.asm'
        with (out/f'{name}.log').open('w') as log:
            subprocess.run([args.assembler, '-binary', '--cpu', 'dcj-11', '--list', str(out/f'{name}.lst'),
                            str(source), str(out/f'{name}.bin')], stdout=log, stderr=subprocess.STDOUT, check=True)
        data = (out/f'{name}.bin').read_bytes()
        assert len(data) <= (480 if name=='sd_boot' else 512) and len(data) % 2 == 0, (name, len(data))
        for i in range(0, len(data), 2):
            words[offset+i//2] = int.from_bytes(data[i:i+2], 'little')
        report[name] = dict(bytes=len(data), source_sha256=hashlib.sha256(source.read_bytes()).hexdigest(),
                            binary_sha256=hashlib.sha256(data).hexdigest())
    assert words[0xf0:0x100]==[0]*16, 'firmware overlaps RK CSR storage'
    report['rk_storage']=dict(first_word=0xf0,words=16,bytes=32,additional_ebr=0)
    # The bus releases RK service only at the historical fixed RTI fetch.
    assert words[256+0o476//2] == 2, 'RK service RTI moved'
    generated = ROOT/'microcode/generated'; generated.mkdir(exist_ok=True)
    (generated/'firmware.mem').write_text(''.join(f'{w:04x}\n' for w in words))
    (generated/'uj11_firmware_rom.v').write_text(generate(words))
    (generated/'firmware.json').write_text(json.dumps(report, indent=2)+'\n')
    print(json.dumps(report, indent=2))


if __name__ == '__main__': main()
