#!/usr/bin/env python3
"""Generate synchronous 1024x9 opcode dispatch table from the readable decoder."""
from pathlib import Path
import subprocess
from make_ebr import lane_initvals
ROOT=Path(__file__).resolve().parents[1]

def generate_table(words):
    # Decode never addresses 280..2bf. During an internal FP transfer both
    # 9-bit ports fetch/write one byte; otherwise A supplies opcode dispatch.
    for i in range(0x280, 0x2c0):
        words[i] = 0
    lines = ['// Generated by tools/build_decode_rom.py; shared decode/FP state EBR.',
             '`timescale 1ns/1ps', 'module uj11_decode_table(',
             ' input wire clk, enable, input wire [9:0] address, output wire [8:0] data,',
             ' input wire fp_enable, fp_write, input wire [4:0] fp_address,',
             ' input wire [15:0] fp_wdata, output wire [15:0] fp_rdata);',
             " wire [9:0] address_a=fp_enable ? {4'b1010,fp_address,1'b0} : address;",
             " wire [9:0] address_b={4'b1010,fp_address,1'b1};",
             ' wire enable_a=enable || fp_enable;',
             ' wire write_fp=fp_enable && fp_write;',
             ' wire [8:0] unused_data_b;',
             ' assign fp_rdata={unused_data_b[7:0],data[7:0]};',
             '`ifdef SYNTHESIS', '`define UJ11_DECODE_EBR',
             '`elsif UJ11_VENDOR_ROM', '`define UJ11_DECODE_EBR', '`endif',
             '`ifdef UJ11_DECODE_EBR', ' DP8KC #(',
             ' .DATA_WIDTH_A(9), .DATA_WIDTH_B(9),',
             ' .REGMODE_A("NOREG"), .REGMODE_B("NOREG"),',
             ' .CSDECODE_A("0b000"), .CSDECODE_B("0b000"),',
             ' .WRITEMODE_A("NORMAL"), .WRITEMODE_B("NORMAL"),',
             ' .GSR("DISABLED"), .RESETMODE("SYNC"),',
             ' .ASYNC_RESET_RELEASE("SYNC"), .INIT_DATA("STATIC"),']
    lines += [f' .INITVAL_{i:02X}("0x{v:080X}"){"," if i < 31 else ""}'
              for i, v in enumerate(lane_initvals(words, 0))]
    lines.append(' ) storage (')
    ports = []
    for side in 'AB':
        ports += [(f'DI{side}{i}', f'fp_wdata[{i+(8 if side=="B" else 0)}]' if i<8 else "1'b0") for i in range(9)]
        for i in range(13):
            ports.append((f'AD{side}{i}', f'address_{side.lower()}[{i-3}]' if i>=3 else ("1'b1" if i==0 else "1'b0")))
        ena='enable_a' if side=='A' else 'fp_enable'
        ports += [(f'CE{side}',ena),(f'OCE{side}',ena),(f'CLK{side}','clk'),(f'WE{side}','write_fp'),(f'RST{side}',"1'b0")]
        ports += [(f'CS{side}{i}',"1'b0") for i in range(3)]
        ports += [(f'DO{side}{i}',f'{"data" if side=="A" else "unused_data_b"}[{i}]') for i in range(9)]
    lines += [f' .{n}({v}){"," if i < len(ports)-1 else ""}' for i,(n,v) in enumerate(ports)]
    lines += [' );', '`else', ' reg [8:0] words[0:1023]; reg [8:0] value_a,value_b;',
              ' initial $readmemh("microcode/generated/decode.mem",words);',
              ' always @(posedge clk) begin',
              "  if(enable_a) begin value_a<=words[address_a]; if(write_fp)words[address_a]<={1'b0,fp_wdata[7:0]}; end",
              "  if(fp_enable) begin value_b<=words[address_b]; if(write_fp)words[address_b]<={1'b0,fp_wdata[15:8]}; end",
              ' end', ' assign data=value_a; assign unused_data_b=value_b;',
              '`endif', '`undef UJ11_DECODE_EBR', 'endmodule', '']
    return '\n'.join(lines)

def main():
    out=ROOT/'build/decode-rom';out.mkdir(parents=True,exist_ok=True)
    (out/'dump.v').write_text('''module dump;
reg [15:0] ir; wire [9:0] entry; integer i;
uj11_decode #(.FP11_CONTROL(1)) dut(ir,entry);
initial begin for(i=0;i<65536;i=i+1)begin ir=i[15:0];#1;$display("%03x",entry);end $finish;end
endmodule
''')
    subprocess.run(['iverilog','-g2012','-s','dump','-o',str(out/'dump'),str(out/'dump.v'),str(ROOT/'rtl/uj11_decode.v')],check=True)
    rows=subprocess.check_output(['vvp',str(out/'dump')],text=True).splitlines()
    truth=[int(s,16) for s in rows if len(s)==3]
    assert len(truth)==65536 and max(truth)<512
    words=[0x42]*1024; seen={}
    for opcode,entry in enumerate(truth):
        group=opcode>>12; memory_mode=int(bool(opcode&0o70))
        if group in (0,8):
            index=(0x100 | ((opcode>>15)<<7) | (((opcode>>6)&63)<<1) | memory_mode) if opcode>>8 else (0x300 | (opcode&255))
        elif group==7:
            index=0x200 | (((opcode>>9)&7)<<3) | (int(bool(opcode&0o700))<<2) | (((opcode>>5)&1)<<1) | memory_mode
        elif group==15:
            index=0x240 | (opcode&0xf) | ((opcode>>2)&0x30) if opcode&0xf30==0 else 0x27f
        else:index=(group<<4) | (int(bool(opcode&0o7000))<<3) | (memory_mode<<2)
        assert not 0x280 <= index < 0x2c0, 'opcode aliases FP state'
        assert index not in seen or seen[index]==entry,(oct(opcode),index,entry,seen.get(index))
        seen[index]=entry;words[index]=entry
    print(f'{len(seen)} addressed rows; exhaustive opcode collision check passed')
    dest=ROOT/'microcode/generated';dest.mkdir(exist_ok=True)
    for i in range(0x280,0x2c0): words[i]=0
    (dest/'decode.mem').write_text(''.join(f'{w:03x}\n' for w in words))
    (dest/'uj11_decode_table.v').write_text(generate_table(words))
    print('Opcode table: 1024 x 9, one EBR')
if __name__=='__main__':main()
