#!/usr/bin/env python3
"""Build isolated MMU CPU microcode. This is not yet a board bitstream."""
import hashlib
import json
from pathlib import Path
import re
import sys
from board_common import ROOT
from make_ebr import generate
sys.path.insert(0,str(ROOT/'microasm'))
from uj11mmuasm import assemble
OUT=ROOT/'build/hc7000-mmu-hardware'
MICROCODE=['microcode/uj11-mmu.uasm','microcode/mmu/odt.uasm','microcode/mmu/fpp.uasm','microcode/mmu/fpp-exec.uasm']
CORE=['rtl/uj11_alu.v','rtl/uj11_decode.v'] + ['rtl/mmu/'+n+'.v' for n in (
    'uj11_mmu_cpu','uj11_mmu_fp_state','uj11_mmu_fp_datapath','uj11_mmu_datapath','uj11_mmu_regfile','uj11_mmu',
    'uj11_mmu_translate','uj11_mmu_apr_ram','uj11_mmu_apr_decode')]
SOURCES=CORE+MICROCODE+['microasm/uj11mmuasm.py','tools/build_mmu.py','tools/make_ebr.py']

def rom(image):
    """Six 1024x9 lanes per bank; the released MMU-less EBR emitter is unchanged."""
    lines=['// GENERATED by tools/build_mmu.py; do not edit.', '`timescale 1ns/1ps',
        'module uj11_mmu_rom #(parameter IMAGE="build/hc7000-mmu-hardware/microcode.mem")(',
        'input wire clk,enable,input wire [11:0] address,output wire [53:0] data);',
        '`ifdef SYNTHESIS','`define UJ11_MMU_EBR','`elsif UJ11_VENDOR_ROM','`define UJ11_MMU_EBR','`endif',
        '`ifdef UJ11_MMU_EBR','wire [53:0] bank0,bank1,bank2; reg [1:0] selected;',
        'always @(posedge clk) if(enable) selected<=address[11:10];',
        "assign data=selected==0 ? bank0 : selected==1 ? bank1 : selected==2 ? bank2 : 54'h0e80000000;"]
    for bank in range(3):
        words=image[bank*1024:(bank+1)*1024]
        groups=[generate([w & ((1<<36)-1) for w in words]),generate([w>>36 for w in words])]
        blocks=[]
        for i,group in enumerate(groups):
            found=re.findall(r'    DP8KC #\([\s\S]*?\n    \);',group)
            assert len(found)==4
            blocks+=found if i==0 else found[:2]
        for lane,block in enumerate(blocks):
            block=re.sub(r'lane_\d+',f'bank{bank}_lane{lane}',block)
            block=block.replace('.CEA(enable)',f'.CEA(enable && address[11:10]==2\'d{bank})')
            block=block.replace('.OCEA(enable)',f'.OCEA(enable && address[11:10]==2\'d{bank})')
            block=re.sub(r'data\[(\d+)\]',lambda m:f'bank{bank}[{int(m[1])+(36 if lane>=4 else 0)}]',block)
            lines.append(block)
    lines += ['`else','reg [53:0] words[0:3071];reg [53:0] value;',
        'initial $readmemh(IMAGE,words);','always @(posedge clk)if(enable)value<=words[address];',
        'assign data=value;','`endif','`undef UJ11_MMU_EBR','endmodule','']
    return '\n'.join(lines)

def build():
    OUT.mkdir(parents=True,exist_ok=True)
    image,listing,labels,stats=assemble('\n'.join((ROOT/p).read_text() for p in MICROCODE))
    (OUT/'microcode.mem').write_text(''.join(f'{w:014x}\n' for w in image))
    (OUT/'microcode.lst').write_text(listing)
    (OUT/'labels.json').write_text(json.dumps(labels,indent=2)+'\n')
    (OUT/'stats.json').write_text(json.dumps(stats,indent=2)+'\n')
    (OUT/'uj11_mmu_rom.v').write_text(rom(image))
    record=dict(cpu='mmu',board='hc7000-lcd-sram',scope='CPU microcode; board manifest is built separately',
        microcode_words=stats['used_words'],physical_words=3072,word_bits=54,microcode_ebr=18,
        files={p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in SOURCES},
        outputs={p:hashlib.sha256((OUT/p).read_bytes()).hexdigest() for p in
                 ('microcode.mem','microcode.lst','labels.json','stats.json','uj11_mmu_rom.v')})
    (OUT/'inputs.json').write_text(json.dumps(record,indent=2)+'\n')
    return record

if __name__=='__main__':
    print(json.dumps({k:v for k,v in build().items() if k not in ('files','outputs')},indent=2))
