#!/usr/bin/env python3
"""Build isolated MMU CPU microcode. This is not yet a board bitstream."""
import hashlib
import json
import os
from pathlib import Path
import re
import sys
from board_common import ROOT
from make_ebr import generate
sys.path.insert(0,str(ROOT/'microasm'))
from uj11mmuasm import assemble
OUT=ROOT/'build/hc7000-mmu-hardware'
MICROCODE=['microcode/uj11-mmu.uasm','microcode/mmu/odt.uasm','microcode/mmu/fpp.uasm','microcode/mmu/fpp-exec.uasm']
CORE=['rtl/uj11_alu.v','rtl/uj11_decode.v'] + ['rtl/mmu/'+n+'.v' for n in (
    'uj11_mmu_cpu','uj11_mmu_fp_state','uj11_mmu_fp_datapath','uj11_mmu_datapath','uj11_mmu_regfile','uj11_mmu',
    'uj11_mmu_translate','uj11_mmu_apr_ram','uj11_mmu_apr_decode')]
SOURCES=CORE+MICROCODE+['microasm/uj11mmuasm.py','tools/build_mmu.py','tools/make_ebr.py']

def fpp_mode(value=None):
    value=value if value is not None else os.environ.get('UJ11_MMU_FPP','microcode')
    if value not in ('microcode','off'):
        raise ValueError('UJ11_MMU_FPP must be microcode or off')
    return value

def rom(image,fpp='microcode'):
    """Six 1024x9 lanes per bank; the released MMU-less EBR emitter is unchanged."""
    if fpp=='off':return compact_rom(image)
    banks=3 if fpp=='microcode' else 2
    lines=['// GENERATED by tools/build_mmu.py; do not edit.', '`timescale 1ns/1ps',
        'module uj11_mmu_rom #(parameter IMAGE="build/hc7000-mmu-hardware/microcode.mem")(',
        'input wire clk,enable,input wire [11:0] address,output wire [53:0] data,output wire fpp_enabled);',
        f"assign fpp_enabled=1'b{int(fpp=='microcode')};",
        '`ifdef SYNTHESIS','`define UJ11_MMU_EBR','`elsif UJ11_VENDOR_ROM','`define UJ11_MMU_EBR','`endif',
        '`ifdef UJ11_MMU_EBR','wire [53:0] bank0,bank1,bank2; reg [1:0] selected;',
        'always @(posedge clk) if(enable) selected<=address[11:10];',
        "assign data=selected==0 ? bank0 : selected==1 ? bank1 : selected==2 ? bank2 : 54'h0e80000000;"]
    if banks==2:
        lines.append("assign bank2=54'h0e80000000;")
    for bank in range(banks):
        words=image[bank*1024:(bank+1)*1024]
        groups=[generate([w & ((1<<36)-1) for w in words]),generate([w>>36 for w in words])]
        blocks=[]
        for i,group in enumerate(groups):
            found=re.findall(r'    DP8KC #\([\s\S]*?\n    \);',group)
            assert len(found)==4
            blocks+=found if i==0 else found[:2]
        for lane,block in enumerate(blocks):
            block=re.sub(r'lane_\d+',f'bank{bank}_lane{lane}',block)
            block=block.replace('.CEA(enable)',f'.CEA(enable && address[11:10]==2\'d{bank})')
            block=block.replace('.OCEA(enable)',f'.OCEA(enable && address[11:10]==2\'d{bank})')
            block=re.sub(r'data\[(\d+)\]',lambda m:f'bank{bank}[{int(m[1])+(36 if lane>=4 else 0)}]',block)
            lines.append(block)
    lines += ['`else','reg [53:0] words[0:3071];reg [53:0] value;',
        'initial $readmemh(IMAGE,words);','always @(posedge clk)if(enable)value<=words[address];',
        'assign data=value;','`endif','`undef UJ11_MMU_EBR','endmodule','']
    return '\n'.join(lines)

def compact_rom(image):
    """Keep the dense first 1K in six EBRs, pack the sparse tail in three.

    Logical microaddresses and every 54-bit word are unchanged. The only
    folded region is 6F0..6FF -> physical 0F0..0FF, unused by page 4.
    Validate the entire mapping, including STOP-filled holes, before emitting.
    """
    stop=0x0e80000000
    def tail_valid(a):return 0x400<=a<0x480 or 0x500<=a<0x600 or 0x6f0<=a<0x700
    tail=[stop]*512
    for a in range(1024,len(image)):
        if tail_valid(a):tail[a&511]=image[a]
    assert all(image[a]==(image[a] if a<1024 else tail[a&511] if tail_valid(a) else stop)
               for a in range(len(image))), 'microcode no longer fits compact ROM mapping'
    # Reuse the established 9-bit lane emitter only for the dense bank.
    dense=rom(image,'microcode')
    blocks=re.findall(r'    DP8KC #\([\s\S]*?\n    \);',dense)[:6]
    lines=['// GENERATED compact MMU ROM: 1536 physical words, nine EBRs.',
        'module uj11_mmu_rom #(parameter IMAGE="build/hc7000-mmu-hardware/microcode.mem")(',
        'input wire clk,enable,input wire [11:0] address,output wire [53:0] data,output wire fpp_enabled);',
        "assign fpp_enabled=1'b0;",
        '`ifdef SYNTHESIS','`define UJ11_MMU_EBR','`elsif UJ11_VENDOR_ROM','`define UJ11_MMU_EBR','`endif',
        '`ifdef UJ11_MMU_EBR','wire [53:0] bank0,tail;reg dense_selected,valid;',
        "wire tail_valid=(address[11:7]==5'h08 || address[11:8]==4'h5 || address[11:4]==8'h6f);",
        'always @(posedge clk)if(enable)begin dense_selected<=address[11:10]==0;valid<=address[11:10]==0 || tail_valid;end',
        "assign data=!valid ? 54'h0e80000000 : dense_selected ? bank0 : tail;"]+blocks
    for lane in range(3):
        lines+=['PDPW8KC #(.DATA_WIDTH_W(18),.DATA_WIDTH_R(18),.REGMODE("NOREG"),',
                ' .CSDECODE_W("0b000"),.CSDECODE_R("0b000"),.GSR("DISABLED"),',
                ' .RESETMODE("SYNC"),.ASYNC_RESET_RELEASE("SYNC"),.INIT_DATA("STATIC"),']
        for b in range(32):
            v=sum(((tail[16*b+n]>>(18*lane))&0x3ffff)<<(20*n) for n in range(16))
            lines.append(f' .INITVAL_{b:02X}("0x{v:080X}"){"," if b<31 else ""}')
        lines.append(f') tail_lane{lane} (')
        ports=[(f'DI{i}',"1'b0") for i in range(18)]
        ports += [(f'DO{i}',f'tail[{18*lane+(i+9 if i<9 else i-9)}]') for i in range(18)]
        ports += [(f'ADW{i}',"1'b0") for i in range(9)]
        ports += [(f'ADR{i}',f'address[{i-4}]' if i>=4 else "1'b0") for i in range(13)]
        ports += [('BE0',"1'b0"),('BE1',"1'b0"),('CEW',"1'b0"),('CER','enable && tail_valid'),
                  ('OCER',"1'b1"),('CLKW','clk'),('CLKR','clk'),('RST',"1'b0")]
        ports += [(f'CS{s}{i}',"1'b0") for s in 'WR' for i in range(3)]
        lines += [f' .{n}({v}){"," if i<len(ports)-1 else ""}' for i,(n,v) in enumerate(ports)]
        lines.append(');')
    lines += ['`else','reg [53:0] words[0:3071];reg [53:0] value;',
        'initial $readmemh(IMAGE,words);','always @(posedge clk)if(enable)value<=words[address];',
        'assign data=value;','`endif','`undef UJ11_MMU_EBR','endmodule','']
    return '\n'.join(lines)

def build(fpp=None):
    fpp=fpp_mode(fpp)
    microcode=MICROCODE if fpp=='microcode' else MICROCODE[:2]
    OUT.mkdir(parents=True,exist_ok=True)
    image,listing,labels,stats=assemble('\n'.join((ROOT/p).read_text() for p in microcode))
    (OUT/'microcode.mem').write_text(''.join(f'{w:014x}\n' for w in image))
    (OUT/'microcode.lst').write_text(listing)
    (OUT/'labels.json').write_text(json.dumps(labels,indent=2)+'\n')
    (OUT/'stats.json').write_text(json.dumps(stats,indent=2)+'\n')
    (OUT/'uj11_mmu_rom.v').write_text(rom(image,fpp))
    record=dict(cpu='mmu',board='hc7000-lcd-sram',fpp=fpp,scope='CPU microcode; board manifest is built separately',
        microcode_words=stats['used_words'],physical_words=3072 if fpp=='microcode' else 1536,
        word_bits=54,microcode_ebr=18 if fpp=='microcode' else 9,
        files={p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in SOURCES
               if p not in MICROCODE or p in microcode},
        outputs={p:hashlib.sha256((OUT/p).read_bytes()).hexdigest() for p in
                 ('microcode.mem','microcode.lst','labels.json','stats.json','uj11_mmu_rom.v')})
    (OUT/'inputs.json').write_text(json.dumps(record,indent=2)+'\n')
    return record

if __name__=='__main__':
    print(json.dumps({k:v for k,v in build().items() if k not in ('files','outputs')},indent=2))
