#!/usr/bin/env python3
"""Emit four explicit 1024x9 MachXO2 DP8KC lanes from assembled uJ11 words.

Physical packing follows the locally vendor-tested AM4 make_mcrom_ebr.py:
two 9-bit words per 20-bit INITVAL slot, 16 slots per INITVAL.
No AM4 microcode or bootstrap data is incorporated.
"""
import argparse
import re
from pathlib import Path


def read_image(path):
    lines = path.read_text().splitlines()
    if len(lines) != 1024 or any(not re.fullmatch(r'[0-9a-fA-F]{9}', s) for s in lines):
        raise ValueError('image must contain exactly 1024 nine-hex-digit words')
    return [int(s, 16) for s in lines]


def lane_initvals(image, lane):
    values = []
    for block in range(32):
        value = 0
        for word in range(32):
            payload = image[block*32 + word] >> (lane*9) & 511
            value |= payload << (20*(word//2) + 9*(word % 2))
        values.append(value)
    return values


def generate(image):
    if len(image) != 1024 or any(w < 0 or w >= 1 << 36 for w in image):
        raise ValueError('expected 1024 unsigned 36-bit words')
    lines = ['// GENERATED by tools/make_ebr.py; do not edit.', '`timescale 1ns/1ps',
             'module uj11_rom #(parameter IMAGE = "unused") (',
             '    input wire clk, enable, input wire [9:0] address,',
             '    output wire [35:0] data', ');']
    for lane in range(4):
        lines += ['    DP8KC #(',
                  '        .DATA_WIDTH_A(9), .DATA_WIDTH_B(9),',
                  '        .REGMODE_A("NOREG"), .REGMODE_B("NOREG"),',
                  '        .CSDECODE_A("0b000"), .CSDECODE_B("0b111"),',
                  '        .WRITEMODE_A("NORMAL"), .WRITEMODE_B("NORMAL"),',
                  '        .GSR("DISABLED"), .RESETMODE("SYNC"),',
                  '        .ASYNC_RESET_RELEASE("SYNC"), .INIT_DATA("STATIC"),']
        initvals = lane_initvals(image, lane)
        lines += [f'        .INITVAL_{i:02X}("0x{x:080X}"){"," if i != 31 else ""}'
                  for i, x in enumerate(initvals)]
        lines += [f'    ) lane_{lane} (']
        ports = []
        for side in 'AB':
            ports += [(f'DI{side}{i}', "1'b0") for i in range(9)]
            for i in range(13):
                val = f'address[{i-3}]' if side == 'A' and i >= 3 else (
                      "1'b1" if side == 'A' and i == 0 else "1'b0")
                ports.append((f'AD{side}{i}', val))
            ports += [(f'CE{side}', 'enable' if side == 'A' else "1'b0"),
                      (f'OCE{side}', 'enable' if side == 'A' else "1'b0"),
                      (f'CLK{side}', 'clk' if side == 'A' else "1'b0"),
                      (f'WE{side}', "1'b0"), (f'RST{side}', "1'b0")]
            ports += [(f'CS{side}{i}', "1'b0") for i in range(3)]
            ports += [(f'DO{side}{i}', f'data[{lane*9+i}]' if side == 'A' else '')
                      for i in range(9)]
        lines += [f'        .{name}({value}){"," if i != len(ports)-1 else ""}'
                  for i, (name, value) in enumerate(ports)]
        lines += ['    );']
    return '\n'.join(lines + ['endmodule', ''])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('image', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    try:
        data = generate(read_image(args.image))
    except (ValueError, OSError) as e:
        parser.exit(1, f'{e}\n')
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(data)


if __name__ == '__main__':
    main()
