#!/usr/bin/env python3
"""Build isolated MMU CPU microcode. This is not yet a board bitstream."""
import hashlib
import json
import os
from pathlib import Path
import re
import sys
from board_common import ROOT
from make_ebr import generate
sys.path.insert(0,str(ROOT/'microasm'))
from uj11mmuasm import assemble
OUT=ROOT/'build/hc7000-mmu-hardware'
MICROCODE=['microcode/uj11-mmu.uasm','microcode/mmu/odt.uasm','microcode/mmu/fpp.uasm','microcode/mmu/fpp-exec.uasm']
CORE=['rtl/uj11_alu.v','rtl/uj11_decode.v'] + ['rtl/mmu/'+n+'.v' for n in (
    'uj11_mmu_cpu','uj11_mmu_decode','uj11_mmu_fp_state','uj11_mmu_fp_datapath','uj11_mmu_datapath','uj11_mmu_regfile','uj11_mmu',
    'uj11_mmu_translate','uj11_mmu_apr_ram','uj11_mmu_apr_decode')]
SOURCES=CORE+MICROCODE+['microasm/uj11mmuasm.py','tools/build_mmu.py','tools/make_ebr.py']

def fpp_mode(value=None):
    value=value if value is not None else os.environ.get('UJ11_MMU_FPP','microcode')
    if value not in ('microcode','off'):
        raise ValueError('UJ11_MMU_FPP must be microcode or off')
    return value

def clock_mhz():
    value=os.environ.get('UJ11_MMU_CLOCK_MHZ','24')
    if value not in ('24','50'):raise ValueError('UJ11_MMU_CLOCK_MHZ must be 24 or 50')
    return int(value)

def pipeline_mode():
    value=os.environ.get('UJ11_MMU_PIPELINE','on' if clock_mhz()==50 else 'off')
    if value not in ('off','on'):raise ValueError('UJ11_MMU_PIPELINE must be off or on')
    if clock_mhz()==50 and value!='on':raise ValueError('50 MHz requires the operand pipeline')
    return value=='on'

def rom(image,fpp='microcode',pipeline=False):
    """Six 1024x9 lanes per bank; the released MMU-less EBR emitter is unchanged."""
    if fpp=='off':return compact_rom(image,pipeline)
    banks=3 if fpp=='microcode' else 2
    lines=['// GENERATED by tools/build_mmu.py; do not edit.', '`timescale 1ns/1ps',
        'module uj11_mmu_rom #(parameter IMAGE="build/hc7000-mmu-hardware/microcode.mem")(',
        'input wire clk,enable,input wire [11:0] address,output wire [53:0] data,output wire fpp_enabled,pipeline_enabled);',
        f"assign fpp_enabled=1'b{int(fpp=='microcode')};",
        f"assign pipeline_enabled=1'b{int(pipeline)};",
        '`ifdef SYNTHESIS','`define UJ11_MMU_EBR','`elsif UJ11_VENDOR_ROM','`define UJ11_MMU_EBR','`endif',
        '`ifdef UJ11_MMU_EBR','wire [53:0] bank0,bank1,bank2; reg [1:0] selected;',
        'always @(posedge clk) if(enable) selected<=address[11:10];',
        "assign data=selected==0 ? bank0 : selected==1 ? bank1 : selected==2 ? bank2 : 54'h0e80000000;"]
    if banks==2:
        lines.append("assign bank2=54'h0e80000000;")
    for bank in range(banks):
        words=image[bank*1024:(bank+1)*1024]
        groups=[generate([w & ((1<<36)-1) for w in words]),generate([w>>36 for w in words])]
        blocks=[]
        for i,group in enumerate(groups):
            found=re.findall(r'    DP8KC #\([\s\S]*?\n    \);',group)
            assert len(found)==4
            blocks+=found if i==0 else found[:2]
        for lane,block in enumerate(blocks):
            block=re.sub(r'lane_\d+',f'bank{bank}_lane{lane}',block)
            # The registered bank selector alone chooses the visible word.
            # Clock all read banks together: decoding next-address bits on
            # EBR clock enable extends the microsequencer's critical path.
            block=re.sub(r'data\[(\d+)\]',lambda m:f'bank{bank}[{int(m[1])+(36 if lane>=4 else 0)}]',block)
            lines.append(block)
    lines += ['`else','reg [53:0] words[0:3071];reg [53:0] value;',
        'initial $readmemh(IMAGE,words);',"always @(posedge clk)if(enable)value<=address<3072 ? words[address] : 54'h0e80000000;",
        'assign data=value;','`endif','`undef UJ11_MMU_EBR','endmodule','']
    return '\n'.join(lines)

def compact_rom(image,pipeline=False):
    """Four dense x9 lanes and two tail x18 lanes; sparse flags in logic.

    Physical storage changes only. Logical microaddresses, 54-bit words,
    clock enable and one-cycle reads must reconstruct the assembled image.
    """
    stop=0x0e80000000
    def tail_valid(a):return 0x400<=a<0x480 or 0x500<=a<0x600 or 0x6f0<=a<0x700
    tail=[stop]*512
    for a in range(1024,len(image)):
        if tail_valid(a):tail[a&511]=image[a]
    assert all(image[a]==(image[a] if a<1024 else tail[a&511] if tail_valid(a) else stop)
               for a in range(len(image))), 'microcode no longer fits compact ROM mapping'
    columns=[];mapping=[]
    for bit in range(54):
        values=tuple((w>>bit)&1 for w in image[:1024])
        if len(set(values))==1:
            mapping.append(('constant',values[0]))
        else:
            if values not in columns:columns.append(values)
            mapping.append(('packed',columns.index(values)))
    if len(columns)>39:
        raise ValueError('Dense microcode exceeds 39 independent columns; revise ROM packing')
    dense=[sum(column[a]<<bit for bit,column in enumerate(columns)) for a in range(1024)]
    if sum(bool(w>>36) for w in dense)>32:
        raise ValueError('Dense microcode exceeds sparse-flag logic budget; revise ROM packing')
    for a,word in enumerate(image[:1024]):
        restored=sum((v if kind=='constant' else (dense[a]>>v)&1)<<bit
                     for bit,(kind,v) in enumerate(mapping))
        assert restored==word,'Dense microcode packing lost bits'
    if any(sum((w>>bit)&1 for w in tail)>128 for bit in range(36,54)):
        raise ValueError('Tail microcode exceeds sparse-flag logic budget; revise ROM packing')
    def flags(output,address,words,bits,width):
        result=[]
        for bit in bits:
            locations=[a for a,w in enumerate(words) if (w>>bit)&1]
            expression=' || '.join(f"{address}=={width}'h{a:x}" for a in locations) or "1'b0"
            result.append(f'assign {output}[{bit}]={expression};')
        return result
    control=(['reg [11:4] selected_region;',
        'always @(posedge clk)if(enable)selected_region<=address[11:4];',
        'wire dense_selected=selected_region[11:10]==0;',
        "wire valid=dense_selected || selected_region[11:7]==5'h08 || selected_region[11:8]==4'h5 || selected_region==8'h6f;"] if pipeline else [
        'reg dense_selected,valid;',
        "wire tail_valid=(address[11:7]==5'h08 || address[11:8]==4'h5 || address[11:4]==8'h6f);",
        'always @(posedge clk)if(enable)begin dense_selected<=address[11:10]==0;valid<=address[11:10]==0 || tail_valid;end'])
    lines=['// GENERATED MMU ROM: six EBRs, lossless 54-bit words; sparse flags in logic.',
        'module uj11_mmu_rom #(parameter IMAGE="build/hc7000-mmu-hardware/microcode.mem")(',
        'input wire clk,enable,input wire [11:0] address,output wire [53:0] data,output wire fpp_enabled,pipeline_enabled);',
        "assign fpp_enabled=1'b0;",f"assign pipeline_enabled=1'b{int(pipeline)};",
        '`ifdef SYNTHESIS','`define UJ11_MMU_EBR','`elsif UJ11_VENDOR_ROM','`define UJ11_MMU_EBR','`endif',
        '`ifdef UJ11_MMU_EBR','wire [53:0] bank0,tail;']+control+[
        "assign data=!valid ? 54'h0e80000000 : dense_selected ? bank0 : tail;",
        'reg [9:0] flag_address;always @(posedge clk)if(enable)flag_address<=address[9:0];',
        'wire [38:0] packed_dense;']
    for bit,(kind,value) in enumerate(mapping):
        lines.append(f'assign bank0[{bit}]='+
                     (f"1'b{value};" if kind=='constant' else f'packed_dense[{value}];'))
    lines+=flags('packed_dense','flag_address',dense,range(36,39),10)
    blocks=re.findall(r'    DP8KC #\([\s\S]*?\n    \);',generate([w&((1<<36)-1) for w in dense]))
    assert len(blocks)==4
    for lane,block in enumerate(blocks):
        block=re.sub(r'lane_\d+',f'bank0_lane{lane}',block)
        lines.append(re.sub(r'data\[(\d+)\]',lambda m:f'packed_dense[{m[1]}]',block))
    lines+=flags('tail','flag_address[8:0]',tail,range(36,54),9)
    for lane in range(2):
        lines+=['PDPW8KC #(.DATA_WIDTH_W(18),.DATA_WIDTH_R(18),.REGMODE("NOREG"),',
                ' .CSDECODE_W("0b000"),.CSDECODE_R("0b000"),.GSR("DISABLED"),',
                ' .RESETMODE("SYNC"),.ASYNC_RESET_RELEASE("SYNC"),.INIT_DATA("STATIC"),']
        for b in range(32):
            v=sum(((tail[16*b+n]>>(18*lane))&0x3ffff)<<(20*n) for n in range(16))
            lines.append(f' .INITVAL_{b:02X}("0x{v:080X}"){"," if b<31 else ""}')
        lines.append(f') tail_lane{lane} (')
        ports=[(f'DI{i}',"1'b0") for i in range(18)]
        ports += [(f'DO{i}',f'tail[{18*lane+(i+9 if i<9 else i-9)}]') for i in range(18)]
        ports += [(f'ADW{i}',"1'b0") for i in range(9)]
        ports += [(f'ADR{i}',f'address[{i-4}]' if i>=4 else "1'b0") for i in range(13)]
        ports += [('BE0',"1'b0"),('BE1',"1'b0"),('CEW',"1'b0"),('CER','enable'),
                  ('OCER',"1'b1"),('CLKW','clk'),('CLKR','clk'),('RST',"1'b0")]
        ports += [(f'CS{s}{i}',"1'b0") for s in 'WR' for i in range(3)]
        lines += [f' .{n}({v}){"," if i<len(ports)-1 else ""}' for i,(n,v) in enumerate(ports)]
        lines.append(');')
    lines += ['`else','reg [53:0] words[0:3071];reg [53:0] value;',
        'initial $readmemh(IMAGE,words);',
        "always @(posedge clk)if(enable)value<=address<3072 ? words[address] : 54'h0e80000000;",
        'assign data=value;','`endif','`undef UJ11_MMU_EBR','endmodule','']
    return '\n'.join(lines)

def build(fpp=None):
    fpp=fpp_mode(fpp)
    microcode=MICROCODE if fpp=='microcode' else MICROCODE[:2]
    OUT.mkdir(parents=True,exist_ok=True)
    image,listing,labels,stats=assemble('\n'.join((ROOT/p).read_text() for p in microcode))
    (OUT/'microcode.mem').write_text(''.join(f'{w:014x}\n' for w in image))
    (OUT/'microcode.lst').write_text(listing)
    (OUT/'labels.json').write_text(json.dumps(labels,indent=2)+'\n')
    (OUT/'stats.json').write_text(json.dumps(stats,indent=2)+'\n')
    pipeline=pipeline_mode()
    (OUT/'uj11_mmu_rom.v').write_text(rom(image,fpp,pipeline))
    record=dict(cpu='mmu',board='hc7000-lcd-sram',fpp=fpp,pipeline=pipeline,clock_mhz=clock_mhz(),scope='CPU microcode; board manifest is built separately',
        microcode_words=stats['used_words'],physical_words=3072 if fpp=='microcode' else 1536,
        word_bits=54,microcode_ebr=18 if fpp=='microcode' else 6,
        files={p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in SOURCES
               if p not in MICROCODE or p in microcode},
        outputs={p:hashlib.sha256((OUT/p).read_bytes()).hexdigest() for p in
                 ('microcode.mem','microcode.lst','labels.json','stats.json','uj11_mmu_rom.v')})
    (OUT/'inputs.json').write_text(json.dumps(record,indent=2)+'\n')
    return record

if __name__=='__main__':
    print(json.dumps({k:v for k,v in build().items() if k not in ('files','outputs')},indent=2))
